"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Activity,
  Tv,
  HeartPulse,
  Radar,
  TrendingUp,
  Clock,
  Gauge,
  HeartHandshake,
  ShieldAlert,
  Dna,
  X,
  Calendar,
  CheckCircle,
} from "lucide-react";

interface Service {
  id: number;
  icon: React.ElementType;
  title: string;
  shortDesc: string;
  longDesc: string;
  indications: string[];
  preparation: string;
}

const SERVICES: Service[] = [
  {
    id: 1,
    icon: Tv,
    title: "Angiography",
    shortDesc: "Advanced imaging test to visualize blockages and blood flow in the coronary arteries.",
    longDesc: "Coronary angiography uses a special contrast dye and X-rays to detect blockages or narrowing in the arteries supplying blood to your heart. It is the gold standard diagnostic tool to determine if a patient needs an angioplasty or bypass surgery.",
    indications: ["Unexplained chest pain (angina)", "Positive Treadmill Test (TMT)", "Shortness of breath", "History of heart attack"],
    preparation: "Requires 6-8 hours of fasting. Certain blood thinners may need to be paused under medical guidance.",
  },
  {
    id: 2,
    icon: Activity,
    title: "Angioplasty",
    shortDesc: "Minimally invasive procedure to open blocked arteries and restore normal blood flow.",
    longDesc: "Also known as Percutaneous Coronary Intervention (PCI), angioplasty opens blocked heart arteries. A small balloon is inflated at the blockage site, and a drug-eluting stent is placed to keep the artery permanently open, preventing future narrowing.",
    indications: ["Severe coronary artery blockages", "Acute heart attack (Primary PCI)", "Worsening chest pain despite medications"],
    preparation: "Requires hospitalization. Full blood panel testing and pre-procedural cardiology assessment are conducted.",
  },
  {
    id: 3,
    icon: HeartPulse,
    title: "Electrocardiogram (ECG)",
    shortDesc: "Quick, painless test that records the electrical activity of your heart to detect issues.",
    longDesc: "An ECG captures the electrical signals generated by your heart. It is the first-line test to detect arrhythmias (irregular heartbeats), myocardial ischemia (inadequate blood flow), and signs of previous or ongoing heart attacks.",
    indications: ["Palpitations or racing heart", "Chest discomfort", "Routine pre-operative clearance", "High blood pressure checks"],
    preparation: "No special preparation needed. Avoid applying heavy body lotions before the test.",
  },
  {
    id: 4,
    icon: Radar,
    title: "2D Echocardiography",
    shortDesc: "High-resolution ultrasound scan to analyze the structure, valves, and pumping capacity.",
    longDesc: "A 2D Echo utilizes sound waves to create live images of your heart. It allows Dr. Kiran to evaluate the thickness of the heart walls, the opening/closing of heart valves, the size of the chambers, and the overall pumping function (Ejection Fraction).",
    indications: ["Heart murmurs", "Unexplained fatigue or breathlessness", "Assessment of heart failure", "Evaluation after a heart attack"],
    preparation: "No preparation required. The test is non-invasive and takes about 15-20 minutes.",
  },
  {
    id: 5,
    icon: TrendingUp,
    title: "Treadmill Test (TMT)",
    shortDesc: "Cardiac stress test to monitor heart activity and blood pressure during exercise.",
    longDesc: "A Treadmill Test (or Stress Test) monitors your ECG, heart rate, and blood pressure while you walk on a treadmill. It helps diagnose coronary artery disease that may remain hidden when your heart is at rest, by measuring how it handles physical exertion.",
    indications: ["Assessment of exertional chest pain", "Evaluation of exercise tolerance", "Screening for coronary disease in high-risk patients"],
    preparation: "Wear comfortable walking shoes and loose clothing. Avoid heavy meals 2 hours before the test.",
  },
  {
    id: 6,
    icon: Clock,
    title: "Holter Monitoring",
    shortDesc: "Continuous 24-48 hour portable ECG to capture irregular heartbeats during daily activities.",
    longDesc: "A Holter Monitor is a small, wearable device that records your heart's electrical activity continuously for 24 to 48 hours. Unlike a brief clinic ECG, it tracks your heart during your regular routine, capturing transient arrhythmias or silent ischemia.",
    indications: ["Frequent unexplained dizziness or fainting", "Intermittent palpitations", "Evaluating effectiveness of arrhythmia medications"],
    preparation: "Shower before the appointment as the device cannot get wet. Wear loose-fitting shirts.",
  },
  {
    id: 7,
    icon: Gauge,
    title: "Hypertension Management",
    shortDesc: "Expert clinical plans to control high blood pressure and prevent stroke or kidney failure.",
    longDesc: "Chronic high blood pressure is a silent killer that damages blood vessels over time. We offer specialized, evidence-based hypertension protocols combining customized pharmacology with advanced dietary counseling to keep your blood pressure in the optimal range.",
    indications: ["Consistently high BP readings (>130/80)", "Headaches, nosebleeds, or blurred vision", "Prevention of cardiovascular stroke"],
    preparation: "Keep a log of your home blood pressure readings (if any) and bring all current medications to your consult.",
  },
  {
    id: 8,
    icon: HeartHandshake,
    title: "Heart Failure Care",
    shortDesc: "Multidisciplinary management to improve heart pumping capacity and quality of life.",
    longDesc: "Heart failure occurs when the heart muscle doesn't pump blood as well as it should. Dr. Kiran provides specialized care paths utilizing state-of-the-art medications, device recommendations (ICD/CRT), and structured salt-fluid restriction guidelines to reduce hospitalizations.",
    indications: ["Swelling in legs, ankles, or abdomen", "Severe breathlessness when lying flat", "Persistent cough with pink phlegm"],
    preparation: "Please bring all recent echocardiogram reports, discharge summaries, and a record of daily fluid intake.",
  },
  {
    id: 9,
    icon: ShieldAlert,
    title: "Preventive Cardiology",
    shortDesc: "Personalized screening and lifestyle therapy to stop heart disease before it starts.",
    longDesc: "Preventive cardiology focuses on identifying and mitigating risk factors early. Through advanced lipid profiling, vascular health checks, and medically-guided dietary and exercise regimens, we help you reverse early atherosclerosis and stay healthy.",
    indications: ["Strong family history of early heart attacks", "High cholesterol levels", "Obesity, sedentary lifestyle, or chronic stress"],
    preparation: "A fasting blood panel is usually required. Fast for 10-12 hours before visiting the clinic.",
  },
  {
    id: 10,
    icon: Dna,
    title: "Diabetes & Heart Care",
    shortDesc: "Focused cardiac screening and vascular protection plans for diabetic individuals.",
    longDesc: "People with diabetes are twice as likely to develop heart disease. Our clinic offers a specialized 'Cardio-Diabetic' program that closely monitors coronary health, manages blood sugar in a heart-safe manner, and protects blood vessels from diabetic damage.",
    indications: ["Type 2 Diabetes Mellitus with cardiac risk", "Co-existing high cholesterol and diabetes", "Symptoms of diabetic neuropathy"],
    preparation: "Bring your latest HbA1c (blood sugar) records and diabetic medications list.",
  },
];

export default function Services() {
  const [selectedService, setSelectedService] = useState<Service | null>(null);

  const handleBookService = () => {
    setSelectedService(null);
    // Smooth scroll to contact
    setTimeout(() => {
      const target = document.querySelector("#contact");
      if (target) {
        const offsetTop = target.getBoundingClientRect().top + window.scrollY - 100;
        window.scrollTo({
          top: offsetTop,
          behavior: "smooth",
        });
      }
    }, 100);
  };

  return (
    <section id="services" className="py-24 bg-white relative">
      <div className="max-w-[1440px] mx-auto px-6 md:px-12">
        
        {/* Header */}
        <div className="flex flex-col items-center text-center max-w-2xl mx-auto mb-16">
          <span className="text-sm font-bold text-primary uppercase tracking-widest mb-3">
            Services
          </span>
          <h2 className="font-heading font-extrabold text-3xl md:text-[48px] text-dark-text tracking-tight leading-tight">
            Comprehensive Cardiac Diagnostic & Treatment Services
          </h2>
          <div className="h-[3px] w-12 bg-primary rounded-full mt-6" />
        </div>

        {/* Services Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {SERVICES.map((service, idx) => {
            const Icon = service.icon;
            return (
              <motion.div
                key={service.id}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.6, delay: Math.min(idx * 0.05, 0.4), ease: "easeOut" }}
                whileHover={{ y: -6 }}
                className="group p-8 rounded-3xl bg-[#F8FAFC] border border-borders/50 hover:border-primary/20 hover:bg-white hover:shadow-xl hover:shadow-primary/5 transition-all duration-300 flex flex-col justify-between items-start text-left cursor-pointer"
                onClick={() => setSelectedService(service)}
              >
                <div>
                  <div className="w-12 h-12 rounded-2xl bg-primary/5 text-primary flex items-center justify-center mb-6 group-hover:bg-primary group-hover:text-white transition-all duration-300 shadow-sm">
                    <Icon className="w-6 h-6" />
                  </div>
                  <h3 className="font-heading font-extrabold text-xl text-dark-text tracking-tight mb-3 group-hover:text-primary transition-colors duration-200">
                    {service.title}
                  </h3>
                  <p className="text-gray-text text-sm leading-relaxed mb-6 font-normal">
                    {service.shortDesc}
                  </p>
                </div>
                <button className="text-sm font-bold text-primary group-hover:text-secondary flex items-center gap-1.5 transition-colors duration-200">
                  <span>Learn More</span>
                  <span className="transform translate-x-0 group-hover:translate-x-1 transition-transform duration-200">→</span>
                </button>
              </motion.div>
            );
          })}
        </div>

        {/* Interactive Detail Modal */}
        <AnimatePresence>
          {selectedService && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 z-50 bg-black/40 backdrop-blur-md flex items-center justify-center p-4"
              onClick={() => setSelectedService(null)}
            >
              {/* Modal Card */}
              <motion.div
                initial={{ scale: 0.95, y: 20, opacity: 0 }}
                animate={{ scale: 1, y: 0, opacity: 1 }}
                exit={{ scale: 0.95, y: 20, opacity: 0 }}
                transition={{ type: "spring", damping: 25, stiffness: 350 }}
                className="bg-white rounded-3xl w-full max-w-2xl overflow-hidden shadow-2xl border border-borders relative flex flex-col max-h-[90vh]"
                onClick={(e) => e.stopPropagation()}
              >
                {/* Header Banner */}
                <div className="p-6 md:p-8 bg-gradient-to-r from-primary to-secondary text-white relative">
                  <button
                    onClick={() => setSelectedService(null)}
                    className="absolute top-6 right-6 p-2 rounded-full bg-white/10 hover:bg-white/20 text-white transition-colors duration-200"
                    aria-label="Close modal"
                  >
                    <X className="w-5 h-5" />
                  </button>
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-2xl bg-white/20 text-white flex items-center justify-center shadow-inner">
                      {(() => {
                        const Icon = selectedService.icon;
                        return <Icon className="w-6 h-6" />;
                      })()}
                    </div>
                    <div>
                      <span className="text-[10px] font-bold tracking-widest uppercase text-white/70">
                        Cardiovascular Service
                      </span>
                      <h4 className="font-heading font-extrabold text-2xl text-white tracking-tight mt-0.5">
                        {selectedService.title}
                      </h4>
                    </div>
                  </div>
                </div>

                {/* Scrollable Body */}
                <div className="p-6 md:p-8 overflow-y-auto flex-1 flex flex-col gap-6 text-left">
                  {/* Detailed Description */}
                  <div>
                    <h5 className="text-xs font-bold uppercase text-primary tracking-wider mb-2">
                      About the Procedure
                    </h5>
                    <p className="text-sm md:text-base text-gray-text font-normal leading-relaxed">
                      {selectedService.longDesc}
                    </p>
                  </div>

                  {/* Common Indications */}
                  <div>
                    <h5 className="text-xs font-bold uppercase text-primary tracking-wider mb-3">
                      When is it recommended?
                    </h5>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      {selectedService.indications.map((ind, i) => (
                        <div key={i} className="flex items-start gap-2 text-sm text-dark-text/90 font-medium">
                          <CheckCircle className="w-4 h-4 text-green-500 shrink-0 mt-0.5" />
                          <span>{ind}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Preparations */}
                  <div className="p-4 rounded-2xl bg-slate-50 border border-borders/60 flex gap-3.5">
                    <div className="w-9 h-9 rounded-xl bg-orange-500/10 text-orange-600 flex items-center justify-center shrink-0">
                      <Clock className="w-5 h-5" />
                    </div>
                    <div className="flex flex-col">
                      <span className="text-xs font-bold text-orange-600 uppercase tracking-wider">
                        Patient Preparation Guidelines
                      </span>
                      <p className="text-xs md:text-sm text-gray-text mt-1 font-medium leading-relaxed">
                        {selectedService.preparation}
                      </p>
                    </div>
                  </div>
                </div>

                {/* Footer Buttons */}
                <div className="p-6 border-t border-borders/60 bg-slate-50 flex items-center justify-end gap-3 shrink-0">
                  <button
                    onClick={() => setSelectedService(null)}
                    className="px-5 py-2.5 rounded-xl border border-borders bg-white font-semibold text-xs text-gray-text hover:bg-slate-50 transition-colors"
                  >
                    Close Details
                  </button>
                  <button
                    onClick={handleBookService}
                    className="px-6 py-2.5 bg-primary text-white font-semibold text-xs rounded-xl hover:bg-secondary shadow-md shadow-primary/10 transition-colors flex items-center gap-2"
                  >
                    <Calendar className="w-4 h-4" />
                    <span>Book Service</span>
                  </button>
                </div>
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </section>
  );
}
